import * as mongoose from 'mongoose';

/**
 * A schema that defines how an object stored in the database should look.
 * ID is not included since it is autogenerated by the database.
 */
export const UserSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
  },
  password: {
    type: Number,
    required: true,
  },
  isAdmin: {
    type: Boolean,
    required: true,
  },
});
