import * as mongoose from 'mongoose';
import * as uniqueValidator from 'mongoose-unique-validator';

/**
 * A schema that defines how an object stored in the database should look.
 * ID is not included since it is autogenerated by the database.
 */
export const UserSchema = new mongoose.Schema({
  email: {
    type: String,
    required: true,
    unique: true,
  },
  password: {
    type: String,
    required: true,
  },
  isAdmin: {
    type: Boolean,
    required: false,
  },
});

UserSchema.plugin(uniqueValidator);
